/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AudioApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AudioApiTests
    {
        private AudioApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AudioApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AudioApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AudioApi
            //Assert.IsInstanceOfType(typeof(AudioApi), instance, "instance is a AudioApi");
        }

        /// <summary>
        /// Test CreateSpeech
        /// </summary>
        [Test]
        public void CreateSpeechTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateSpeechRequest body = null;
            //var response = instance.CreateSpeech(body);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        /// <summary>
        /// Test CreateTranscription
        /// </summary>
        [Test]
        public void CreateTranscriptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //byte[] file = null;
            //Object model = null;
            //string language = null;
            //string prompt = null;
            //string responseFormat = null;
            //decimal? temperature = null;
            //var response = instance.CreateTranscription(file, model, language, prompt, responseFormat, temperature);
            //Assert.IsInstanceOf<CreateTranscriptionResponse> (response, "response is CreateTranscriptionResponse");
        }
        /// <summary>
        /// Test CreateTranslation
        /// </summary>
        [Test]
        public void CreateTranslationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //byte[] file = null;
            //Object model = null;
            //string prompt = null;
            //string responseFormat = null;
            //decimal? temperature = null;
            //var response = instance.CreateTranslation(file, model, prompt, responseFormat, temperature);
            //Assert.IsInstanceOf<CreateTranslationResponse> (response, "response is CreateTranslationResponse");
        }
    }

}
