/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace IO.Swagger.Model
{
    /// <summary>
    /// AnyOfCreateImageEditRequestModel
    /// </summary>
    public interface AnyOfCreateImageEditRequestModel
    {
    
    }
}
