/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// A chat completion delta generated by streamed model responses.
    /// </summary>
    [DataContract]
        public partial class ChatCompletionStreamResponseDelta :  IEquatable<ChatCompletionStreamResponseDelta>, IValidatableObject
    {
        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        /// <value>The role of the author of this message.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum RoleEnum
        {
            /// <summary>
            /// Enum System for value: system
            /// </summary>
            [EnumMember(Value = "system")]
            System = 1,
            /// <summary>
            /// Enum User for value: user
            /// </summary>
            [EnumMember(Value = "user")]
            User = 2,
            /// <summary>
            /// Enum Assistant for value: assistant
            /// </summary>
            [EnumMember(Value = "assistant")]
            Assistant = 3,
            /// <summary>
            /// Enum Tool for value: tool
            /// </summary>
            [EnumMember(Value = "tool")]
            Tool = 4        }
        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        /// <value>The role of the author of this message.</value>
        [DataMember(Name="role", EmitDefaultValue=false)]
        public RoleEnum? Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionStreamResponseDelta" /> class.
        /// </summary>
        /// <param name="content">The contents of the chunk message..</param>
        /// <param name="functionCall">functionCall.</param>
        /// <param name="toolCalls">toolCalls.</param>
        /// <param name="role">The role of the author of this message..</param>
        public ChatCompletionStreamResponseDelta(string content = default(string), ChatCompletionStreamResponseDeltaFunctionCall functionCall = default(ChatCompletionStreamResponseDeltaFunctionCall), List<ChatCompletionMessageToolCallChunk> toolCalls = default(List<ChatCompletionMessageToolCallChunk>), RoleEnum? role = default(RoleEnum?))
        {
            this.Content = content;
            this.FunctionCall = functionCall;
            this.ToolCalls = toolCalls;
            this.Role = role;
        }
        
        /// <summary>
        /// The contents of the chunk message.
        /// </summary>
        /// <value>The contents of the chunk message.</value>
        [DataMember(Name="content", EmitDefaultValue=false)]
        public string Content { get; set; }

        /// <summary>
        /// Gets or Sets FunctionCall
        /// </summary>
        [DataMember(Name="function_call", EmitDefaultValue=false)]
        public ChatCompletionStreamResponseDeltaFunctionCall FunctionCall { get; set; }

        /// <summary>
        /// Gets or Sets ToolCalls
        /// </summary>
        [DataMember(Name="tool_calls", EmitDefaultValue=false)]
        public List<ChatCompletionMessageToolCallChunk> ToolCalls { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChatCompletionStreamResponseDelta {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  FunctionCall: ").Append(FunctionCall).Append("\n");
            sb.Append("  ToolCalls: ").Append(ToolCalls).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChatCompletionStreamResponseDelta);
        }

        /// <summary>
        /// Returns true if ChatCompletionStreamResponseDelta instances are equal
        /// </summary>
        /// <param name="input">Instance of ChatCompletionStreamResponseDelta to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChatCompletionStreamResponseDelta input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.FunctionCall == input.FunctionCall ||
                    (this.FunctionCall != null &&
                    this.FunctionCall.Equals(input.FunctionCall))
                ) && 
                (
                    this.ToolCalls == input.ToolCalls ||
                    this.ToolCalls != null &&
                    input.ToolCalls != null &&
                    this.ToolCalls.SequenceEqual(input.ToolCalls)
                ) && 
                (
                    this.Role == input.Role ||
                    (this.Role != null &&
                    this.Role.Equals(input.Role))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Content != null)
                    hashCode = hashCode * 59 + this.Content.GetHashCode();
                if (this.FunctionCall != null)
                    hashCode = hashCode * 59 + this.FunctionCall.GetHashCode();
                if (this.ToolCalls != null)
                    hashCode = hashCode * 59 + this.ToolCalls.GetHashCode();
                if (this.Role != null)
                    hashCode = hashCode * 59 + this.Role.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
