/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateCompletionResponseChoices
    /// </summary>
    [DataContract]
        public partial class CreateCompletionResponseChoices :  IEquatable<CreateCompletionResponseChoices>, IValidatableObject
    {
        /// <summary>
        /// The reason the model stopped generating tokens. This will be &#x60;stop&#x60; if the model hit a natural stop point or a provided stop sequence, &#x60;length&#x60; if the maximum number of tokens specified in the request was reached, or &#x60;content_filter&#x60; if content was omitted due to a flag from our content filters. 
        /// </summary>
        /// <value>The reason the model stopped generating tokens. This will be &#x60;stop&#x60; if the model hit a natural stop point or a provided stop sequence, &#x60;length&#x60; if the maximum number of tokens specified in the request was reached, or &#x60;content_filter&#x60; if content was omitted due to a flag from our content filters. </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum FinishReasonEnum
        {
            /// <summary>
            /// Enum Stop for value: stop
            /// </summary>
            [EnumMember(Value = "stop")]
            Stop = 1,
            /// <summary>
            /// Enum Length for value: length
            /// </summary>
            [EnumMember(Value = "length")]
            Length = 2,
            /// <summary>
            /// Enum Contentfilter for value: content_filter
            /// </summary>
            [EnumMember(Value = "content_filter")]
            Contentfilter = 3        }
        /// <summary>
        /// The reason the model stopped generating tokens. This will be &#x60;stop&#x60; if the model hit a natural stop point or a provided stop sequence, &#x60;length&#x60; if the maximum number of tokens specified in the request was reached, or &#x60;content_filter&#x60; if content was omitted due to a flag from our content filters. 
        /// </summary>
        /// <value>The reason the model stopped generating tokens. This will be &#x60;stop&#x60; if the model hit a natural stop point or a provided stop sequence, &#x60;length&#x60; if the maximum number of tokens specified in the request was reached, or &#x60;content_filter&#x60; if content was omitted due to a flag from our content filters. </value>
        [DataMember(Name="finish_reason", EmitDefaultValue=false)]
        public FinishReasonEnum FinishReason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCompletionResponseChoices" /> class.
        /// </summary>
        /// <param name="finishReason">The reason the model stopped generating tokens. This will be &#x60;stop&#x60; if the model hit a natural stop point or a provided stop sequence, &#x60;length&#x60; if the maximum number of tokens specified in the request was reached, or &#x60;content_filter&#x60; if content was omitted due to a flag from our content filters.  (required).</param>
        /// <param name="index">index (required).</param>
        /// <param name="logprobs">logprobs (required).</param>
        /// <param name="text">text (required).</param>
        public CreateCompletionResponseChoices(FinishReasonEnum finishReason = default(FinishReasonEnum), int? index = default(int?), CreateCompletionResponseLogprobs logprobs = default(CreateCompletionResponseLogprobs), string text = default(string))
        {
            // to ensure "finishReason" is required (not null)
            if (finishReason == null)
            {
                throw new InvalidDataException("finishReason is a required property for CreateCompletionResponseChoices and cannot be null");
            }
            else
            {
                this.FinishReason = finishReason;
            }
            // to ensure "index" is required (not null)
            if (index == null)
            {
                throw new InvalidDataException("index is a required property for CreateCompletionResponseChoices and cannot be null");
            }
            else
            {
                this.Index = index;
            }
            // to ensure "logprobs" is required (not null)
            if (logprobs == null)
            {
                throw new InvalidDataException("logprobs is a required property for CreateCompletionResponseChoices and cannot be null");
            }
            else
            {
                this.Logprobs = logprobs;
            }
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new InvalidDataException("text is a required property for CreateCompletionResponseChoices and cannot be null");
            }
            else
            {
                this.Text = text;
            }
        }
        

        /// <summary>
        /// Gets or Sets Index
        /// </summary>
        [DataMember(Name="index", EmitDefaultValue=false)]
        public int? Index { get; set; }

        /// <summary>
        /// Gets or Sets Logprobs
        /// </summary>
        [DataMember(Name="logprobs", EmitDefaultValue=false)]
        public CreateCompletionResponseLogprobs Logprobs { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCompletionResponseChoices {\n");
            sb.Append("  FinishReason: ").Append(FinishReason).Append("\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  Logprobs: ").Append(Logprobs).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCompletionResponseChoices);
        }

        /// <summary>
        /// Returns true if CreateCompletionResponseChoices instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCompletionResponseChoices to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCompletionResponseChoices input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FinishReason == input.FinishReason ||
                    (this.FinishReason != null &&
                    this.FinishReason.Equals(input.FinishReason))
                ) && 
                (
                    this.Index == input.Index ||
                    (this.Index != null &&
                    this.Index.Equals(input.Index))
                ) && 
                (
                    this.Logprobs == input.Logprobs ||
                    (this.Logprobs != null &&
                    this.Logprobs.Equals(input.Logprobs))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FinishReason != null)
                    hashCode = hashCode * 59 + this.FinishReason.GetHashCode();
                if (this.Index != null)
                    hashCode = hashCode * 59 + this.Index.GetHashCode();
                if (this.Logprobs != null)
                    hashCode = hashCode * 59 + this.Logprobs.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
