/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// The last error associated with this run. Will be &#x60;null&#x60; if there are no errors.
    /// </summary>
    [DataContract]
        public partial class RunObjectLastError :  IEquatable<RunObjectLastError>, IValidatableObject
    {
        /// <summary>
        /// One of &#x60;server_error&#x60; or &#x60;rate_limit_exceeded&#x60;.
        /// </summary>
        /// <value>One of &#x60;server_error&#x60; or &#x60;rate_limit_exceeded&#x60;.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum CodeEnum
        {
            /// <summary>
            /// Enum Servererror for value: server_error
            /// </summary>
            [EnumMember(Value = "server_error")]
            Servererror = 1,
            /// <summary>
            /// Enum Ratelimitexceeded for value: rate_limit_exceeded
            /// </summary>
            [EnumMember(Value = "rate_limit_exceeded")]
            Ratelimitexceeded = 2        }
        /// <summary>
        /// One of &#x60;server_error&#x60; or &#x60;rate_limit_exceeded&#x60;.
        /// </summary>
        /// <value>One of &#x60;server_error&#x60; or &#x60;rate_limit_exceeded&#x60;.</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunObjectLastError" /> class.
        /// </summary>
        /// <param name="code">One of &#x60;server_error&#x60; or &#x60;rate_limit_exceeded&#x60;. (required).</param>
        /// <param name="message">A human-readable description of the error. (required).</param>
        public RunObjectLastError(CodeEnum code = default(CodeEnum), string message = default(string))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for RunObjectLastError and cannot be null");
            }
            else
            {
                this.Code = code;
            }
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new InvalidDataException("message is a required property for RunObjectLastError and cannot be null");
            }
            else
            {
                this.Message = message;
            }
        }
        

        /// <summary>
        /// A human-readable description of the error.
        /// </summary>
        /// <value>A human-readable description of the error.</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RunObjectLastError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RunObjectLastError);
        }

        /// <summary>
        /// Returns true if RunObjectLastError instances are equal
        /// </summary>
        /// <param name="input">Instance of RunObjectLastError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RunObjectLastError input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
