/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChatCompletionRequestAssistantMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChatCompletionRequestAssistantMessageTests
    {
        // TODO uncomment below to declare an instance variable for ChatCompletionRequestAssistantMessage
        //private ChatCompletionRequestAssistantMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChatCompletionRequestAssistantMessage
            //instance = new ChatCompletionRequestAssistantMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChatCompletionRequestAssistantMessage
        /// </summary>
        [Test]
        public void ChatCompletionRequestAssistantMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChatCompletionRequestAssistantMessage
            //Assert.IsInstanceOfType<ChatCompletionRequestAssistantMessage> (instance, "variable 'instance' is a ChatCompletionRequestAssistantMessage");
        }


        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'ToolCalls'
        /// </summary>
        [Test]
        public void ToolCallsTest()
        {
            // TODO unit test for the property 'ToolCalls'
        }
        /// <summary>
        /// Test the property 'FunctionCall'
        /// </summary>
        [Test]
        public void FunctionCallTest()
        {
            // TODO unit test for the property 'FunctionCall'
        }

    }

}
