/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateChatCompletionImageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateChatCompletionImageResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateChatCompletionImageResponse
        //private CreateChatCompletionImageResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateChatCompletionImageResponse
            //instance = new CreateChatCompletionImageResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateChatCompletionImageResponse
        /// </summary>
        [Test]
        public void CreateChatCompletionImageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateChatCompletionImageResponse
            //Assert.IsInstanceOfType<CreateChatCompletionImageResponse> (instance, "variable 'instance' is a CreateChatCompletionImageResponse");
        }



    }

}
