/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateThreadAndRunRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateThreadAndRunRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateThreadAndRunRequest
        //private CreateThreadAndRunRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateThreadAndRunRequest
            //instance = new CreateThreadAndRunRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateThreadAndRunRequest
        /// </summary>
        [Test]
        public void CreateThreadAndRunRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateThreadAndRunRequest
            //Assert.IsInstanceOfType<CreateThreadAndRunRequest> (instance, "variable 'instance' is a CreateThreadAndRunRequest");
        }


        /// <summary>
        /// Test the property 'AssistantId'
        /// </summary>
        [Test]
        public void AssistantIdTest()
        {
            // TODO unit test for the property 'AssistantId'
        }
        /// <summary>
        /// Test the property 'Thread'
        /// </summary>
        [Test]
        public void ThreadTest()
        {
            // TODO unit test for the property 'Thread'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'Tools'
        /// </summary>
        [Test]
        public void ToolsTest()
        {
            // TODO unit test for the property 'Tools'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
