/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateChatCompletionStreamResponseChoices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateChatCompletionStreamResponseChoicesTests
    {
        // TODO uncomment below to declare an instance variable for CreateChatCompletionStreamResponseChoices
        //private CreateChatCompletionStreamResponseChoices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateChatCompletionStreamResponseChoices
            //instance = new CreateChatCompletionStreamResponseChoices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateChatCompletionStreamResponseChoices
        /// </summary>
        [Test]
        public void CreateChatCompletionStreamResponseChoicesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateChatCompletionStreamResponseChoices
            //Assert.IsInstanceOfType<CreateChatCompletionStreamResponseChoices> (instance, "variable 'instance' is a CreateChatCompletionStreamResponseChoices");
        }


        /// <summary>
        /// Test the property 'Delta'
        /// </summary>
        [Test]
        public void DeltaTest()
        {
            // TODO unit test for the property 'Delta'
        }
        /// <summary>
        /// Test the property 'FinishReason'
        /// </summary>
        [Test]
        public void FinishReasonTest()
        {
            // TODO unit test for the property 'FinishReason'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

    }

}
