/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateImageVariationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateImageVariationRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateImageVariationRequest
        //private CreateImageVariationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateImageVariationRequest
            //instance = new CreateImageVariationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateImageVariationRequest
        /// </summary>
        [Test]
        public void CreateImageVariationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateImageVariationRequest
            //Assert.IsInstanceOfType<CreateImageVariationRequest> (instance, "variable 'instance' is a CreateImageVariationRequest");
        }


        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Test]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }
        /// <summary>
        /// Test the property 'ResponseFormat'
        /// </summary>
        [Test]
        public void ResponseFormatTest()
        {
            // TODO unit test for the property 'ResponseFormat'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
