/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Image
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImageTests
    {
        // TODO uncomment below to declare an instance variable for Image
        //private Image instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Image
            //instance = new Image();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Image
        /// </summary>
        [Test]
        public void ImageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Image
            //Assert.IsInstanceOfType<Image> (instance, "variable 'instance' is a Image");
        }


        /// <summary>
        /// Test the property 'B64Json'
        /// </summary>
        [Test]
        public void B64JsonTest()
        {
            // TODO unit test for the property 'B64Json'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'RevisedPrompt'
        /// </summary>
        [Test]
        public void RevisedPromptTest()
        {
            // TODO unit test for the property 'RevisedPrompt'
        }

    }

}
