/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OneOfChatCompletionRequestUserMessageContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfChatCompletionRequestUserMessageContentTests
    {
        // TODO uncomment below to declare an instance variable for OneOfChatCompletionRequestUserMessageContent
        //private OneOfChatCompletionRequestUserMessageContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfChatCompletionRequestUserMessageContent
            //instance = new OneOfChatCompletionRequestUserMessageContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfChatCompletionRequestUserMessageContent
        /// </summary>
        [Test]
        public void OneOfChatCompletionRequestUserMessageContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfChatCompletionRequestUserMessageContent
            //Assert.IsInstanceOfType<OneOfChatCompletionRequestUserMessageContent> (instance, "variable 'instance' is a OneOfChatCompletionRequestUserMessageContent");
        }



    }

}
