/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OneOfCreateCompletionRequestPrompt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfCreateCompletionRequestPromptTests
    {
        // TODO uncomment below to declare an instance variable for OneOfCreateCompletionRequestPrompt
        //private OneOfCreateCompletionRequestPrompt instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfCreateCompletionRequestPrompt
            //instance = new OneOfCreateCompletionRequestPrompt();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfCreateCompletionRequestPrompt
        /// </summary>
        [Test]
        public void OneOfCreateCompletionRequestPromptInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfCreateCompletionRequestPrompt
            //Assert.IsInstanceOfType<OneOfCreateCompletionRequestPrompt> (instance, "variable 'instance' is a OneOfCreateCompletionRequestPrompt");
        }



    }

}
