/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OpenAIFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OpenAIFileTests
    {
        // TODO uncomment below to declare an instance variable for OpenAIFile
        //private OpenAIFile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OpenAIFile
            //instance = new OpenAIFile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OpenAIFile
        /// </summary>
        [Test]
        public void OpenAIFileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OpenAIFile
            //Assert.IsInstanceOfType<OpenAIFile> (instance, "variable 'instance' is a OpenAIFile");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Test]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }
        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Test]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDetails'
        /// </summary>
        [Test]
        public void StatusDetailsTest()
        {
            // TODO unit test for the property 'StatusDetails'
        }

    }

}
