/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RunObjectRequiredAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RunObjectRequiredActionTests
    {
        // TODO uncomment below to declare an instance variable for RunObjectRequiredAction
        //private RunObjectRequiredAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RunObjectRequiredAction
            //instance = new RunObjectRequiredAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunObjectRequiredAction
        /// </summary>
        [Test]
        public void RunObjectRequiredActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RunObjectRequiredAction
            //Assert.IsInstanceOfType<RunObjectRequiredAction> (instance, "variable 'instance' is a RunObjectRequiredAction");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SubmitToolOutputs'
        /// </summary>
        [Test]
        public void SubmitToolOutputsTest()
        {
            // TODO unit test for the property 'SubmitToolOutputs'
        }

    }

}
