/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RunStepDetailsMessageCreationObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RunStepDetailsMessageCreationObjectTests
    {
        // TODO uncomment below to declare an instance variable for RunStepDetailsMessageCreationObject
        //private RunStepDetailsMessageCreationObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RunStepDetailsMessageCreationObject
            //instance = new RunStepDetailsMessageCreationObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunStepDetailsMessageCreationObject
        /// </summary>
        [Test]
        public void RunStepDetailsMessageCreationObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RunStepDetailsMessageCreationObject
            //Assert.IsInstanceOfType<RunStepDetailsMessageCreationObject> (instance, "variable 'instance' is a RunStepDetailsMessageCreationObject");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'MessageCreation'
        /// </summary>
        [Test]
        public void MessageCreationTest()
        {
            // TODO unit test for the property 'MessageCreation'
        }

    }

}
