/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RunStepDetailsMessageCreationObjectMessageCreation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RunStepDetailsMessageCreationObjectMessageCreationTests
    {
        // TODO uncomment below to declare an instance variable for RunStepDetailsMessageCreationObjectMessageCreation
        //private RunStepDetailsMessageCreationObjectMessageCreation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RunStepDetailsMessageCreationObjectMessageCreation
            //instance = new RunStepDetailsMessageCreationObjectMessageCreation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunStepDetailsMessageCreationObjectMessageCreation
        /// </summary>
        [Test]
        public void RunStepDetailsMessageCreationObjectMessageCreationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RunStepDetailsMessageCreationObjectMessageCreation
            //Assert.IsInstanceOfType<RunStepDetailsMessageCreationObjectMessageCreation> (instance, "variable 'instance' is a RunStepDetailsMessageCreationObjectMessageCreation");
        }


        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Test]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

    }

}
