/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RunStepDetailsToolCallsRetrievalObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RunStepDetailsToolCallsRetrievalObjectTests
    {
        // TODO uncomment below to declare an instance variable for RunStepDetailsToolCallsRetrievalObject
        //private RunStepDetailsToolCallsRetrievalObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RunStepDetailsToolCallsRetrievalObject
            //instance = new RunStepDetailsToolCallsRetrievalObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunStepDetailsToolCallsRetrievalObject
        /// </summary>
        [Test]
        public void RunStepDetailsToolCallsRetrievalObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RunStepDetailsToolCallsRetrievalObject
            //Assert.IsInstanceOfType<RunStepDetailsToolCallsRetrievalObject> (instance, "variable 'instance' is a RunStepDetailsToolCallsRetrievalObject");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Retrieval'
        /// </summary>
        [Test]
        public void RetrievalTest()
        {
            // TODO unit test for the property 'Retrieval'
        }

    }

}
