/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RunStepObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RunStepObjectTests
    {
        // TODO uncomment below to declare an instance variable for RunStepObject
        //private RunStepObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RunStepObject
            //instance = new RunStepObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunStepObject
        /// </summary>
        [Test]
        public void RunStepObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RunStepObject
            //Assert.IsInstanceOfType<RunStepObject> (instance, "variable 'instance' is a RunStepObject");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'AssistantId'
        /// </summary>
        [Test]
        public void AssistantIdTest()
        {
            // TODO unit test for the property 'AssistantId'
        }
        /// <summary>
        /// Test the property 'ThreadId'
        /// </summary>
        [Test]
        public void ThreadIdTest()
        {
            // TODO unit test for the property 'ThreadId'
        }
        /// <summary>
        /// Test the property 'RunId'
        /// </summary>
        [Test]
        public void RunIdTest()
        {
            // TODO unit test for the property 'RunId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StepDetails'
        /// </summary>
        [Test]
        public void StepDetailsTest()
        {
            // TODO unit test for the property 'StepDetails'
        }
        /// <summary>
        /// Test the property 'LastError'
        /// </summary>
        [Test]
        public void LastErrorTest()
        {
            // TODO unit test for the property 'LastError'
        }
        /// <summary>
        /// Test the property 'ExpiredAt'
        /// </summary>
        [Test]
        public void ExpiredAtTest()
        {
            // TODO unit test for the property 'ExpiredAt'
        }
        /// <summary>
        /// Test the property 'CancelledAt'
        /// </summary>
        [Test]
        public void CancelledAtTest()
        {
            // TODO unit test for the property 'CancelledAt'
        }
        /// <summary>
        /// Test the property 'FailedAt'
        /// </summary>
        [Test]
        public void FailedAtTest()
        {
            // TODO unit test for the property 'FailedAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Test]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
